### PR TITLE
Adapt secure vault config changes from puppet base

### LINKED ISSUE #40: Adapt secure vault config changes from puppet base
Applying secure vault configurations via puppet templates is removed in puppet base. Instead, we simply copy the secure vault files via puppet file resources. This change needs to be adapted in order to ensure the functionality of secure vault

### PR DESCRIPTION
**Pull request by vidurananayakkara**
Resolves #40

### CODE REVIEW

**Review by chamilad — APPROVED** [review]
LGTM!

**Comment by pubudu538** [comment]
Let's not add any changes to 2.1.0 branch. We can do all the latest fixes, improvements to master branch and do a release from master branch.

**Comment by vidurananayakkara** [comment]
@pubudu538 Without this change secure vault will not work in APIM 2.1.0 with the latest puppet-base (upcoming release) (with this change secure vault will not work when old puppet base is used). Since the APIM 3.0.0 deployment method is different these changes would anyway be not applicable for APIM 3.0.0 and would not make sense to have these changes in the master branch only. Shouldn't we release these changes as a patch release (APIM 2.1.0.1) (In that case I will point this pull request to APIM 2.1.0.1 branch)

**Comment by pubudu538** [comment]
We will do any active development on master branch. For any patch releases in APIM 2.1.0, we can create a branch from master branch and release. At the moment, we don't have plans to use puppet for APIM 300.

**Comment by vidurananayakkara** [comment]
Closing this PR based on the above comment. Patch release for puppet-apim-2.1.0 will be released from the master branch

**Pull request closed without merging**
