### PR TITLE
Typos in code comments

### PR DESCRIPTION
**Pull request by ricksbrown**
## Purpose
Fix typos in the documentation

## Goals
Increase the professionalism of your product.

## Approach
N/A

## User stories
N/A

## Release note
Fixed typos in puppet manifests.

## Documentation
N/A

## Training
N/A

## Certification
N/A

## Marketing
N/A

## Automation tests
N/A

## Security checks
N/A

## Samples
N/A

## Related PRs
N/A

## Migrations (if applicable)
N/A

## Test environment
 N/A

## Learning
N/A

### CODE REVIEW

**Comment by ctienshi** [comment]
Closing since it is already fixed.

**Comment by ricksbrown** [comment]
doesn't look "already fixed" to me

**Comment by ctienshi** [comment]
@Savidude Could you please check?

**Comment by Savidude** [comment]
Hi @ricksbrown,

We have made some major changes to our Puppet modules. While making those changes, we have also fixed typos, formatting, and other minor code level issues [1]. Please let us know if you have identified any typos (or any other mistakes) that have not been fixed.

[1] https://github.com/wso2/puppet-apim/commit/565d8369f4263f61e55aab998d0ff75dba7b1e07#diff-0870b265dfc1f7618dbef6aecd137e26

Thanks :)

**Pull request closed without merging**
